# Generated by Django 3.2.7 on 2021-09-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_toolbox'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toolbox',
            new_name='Tool',
        ),
    ]
