# Generated by Django 3.2.7 on 2021-09-02 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210902_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tagcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.tagcategory'),
        ),
    ]
