# Generated by Django 3.2.7 on 2021-09-02 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_tag_tagcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcategory',
            name='hierarchy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tag', to='portfolio.tagcategory'),
        ),
    ]
