# Generated by Django 3.2.7 on 2021-09-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210902_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcategory',
            name='hierarchy',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
