# Generated by Django 3.2.7 on 2021-09-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_project_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
