# Generated by Django 3.2.7 on 2021-11-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_alter_cvroleitem_cv_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='hierarchy',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
    ]
